----------------------------------------------------------
# Cost function of the Linear regrestion 
1. MSE(Mean Square Error)
   *  This Equation is differentiable.
    * This equation also has one global minima .
2. MAE ( Mean absulote error)
3. RMSE(root mean sequare error)

Q. What is the heber loss ?

--------------------------------------------------------

# 1. Performance Matrix

* R squared 
* Adjusted R squared.

####  R squared 
    1- SSres/ SS Total  ( SS Res = sum of square residuals , SS Total = sum of square average)

----------------------

# Overfiting And Under Fitting (Bias and Variance)

## EDA

df.duplicated() -> sabai duplicate vayeko thauma True value dinxa

# df[df.duplicated]
# drop the dupblicate value 
# df[df.duplicated]

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame([1,2,3,4,5,5,6,6,6,7,7,7,7,9])
df

    0
0   1
1   2
2   3
3   4
4   5
5   5
6   6
7   6
8   6
9   7
10  7
11  7
12  7
13  9

In [6]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7      True
8      True
9     False
10     True
11     True
12     True
13    False
dtype: bool

In [5]:
df[df.duplicated]

    0
5   5
7   6
8   6
10  7
11  7
12  7

In [8]:
df.drop_duplicates()

    0
0   1
1   2
2   3
3   4
4   5
6   6
9   7
13  9